### ISSUE TITLE
The Hammers applied can conceal?

### ISSUE THREAD

**Issue by a90493x14** [PirateIzzy/WzComparerR2#1]
And WzComparerR2 have other language?
Like Japanese or Chinese traditional. 
Thank you for reply my lssues！

**Comment by PirateIzzy** [comment]
Terribly sorry for not noticing this before. I can look into how to hide the () attribute.

**Comment by PirateIzzy** [comment]
I was able to conceal the Hammers a while ago, and have updated it accordingly.
