### ISSUE TITLE
Patcher results in error in .NET 6.0 version

### ISSUE THREAD

**Issue by PirateIzzy** [PirateIzzy/WzComparerR2#6]
When attempting to patch in the .NET 6.0 version, the patcher will throw a Checksum Error upon starting the post-patch checksum verification. 

Findings:

1. This issue can consistently be replicated, regardless of the MS version (KMS, CMS, etc)

2. The error message and hashcode are consistent when attempting to patch the same version; otherwise the hashcode will be different. Here was the hashcode given with KMS v383 -> v384
![image](https://github.com/PirateIzzy/WzComparerR2/assets/34289651/c3e6ff1d-20fe-4901-8173-19bfeac8dc0e)

And here was the hashcode given with CMS v202 -> v203
![image (2)](https://github.com/PirateIzzy/WzComparerR2/assets/34289651/7e1fec4f-2fb9-4b06-9b64-1d3cab95ac59)

3. This error only occurs in the WCR2-GMS fork's .NET 6.0 version; it does not occur with the .NET 4.6.2 version, nor does it occur in Kagamia's .NET 6.0 version.

4. The lines referenced are as follows:
WzPatcher.cs:
https://github.com/PirateIzzy/WzComparerR2/blob/07495ba9b7107b438f7050d00a26f71f012f23b9/WzComparerR2/Patcher/WzPatcher.cs#L879
https://github.com/PirateIzzy/WzComparerR2/blob/07495ba9b7107b438f7050d00a26f71f012f23b9/WzComparerR2/Patcher/WzPatcher.cs#L515
https://github.com/PirateIzzy/WzComparerR2/blob/07495ba9b7107b438f7050d00a26f71f012f23b9/WzComparerR2/Patcher/WzPatcher.cs#L333
FrmPatcher.cs
https://github.com/PirateIzzy/WzComparerR2/blob/07495ba9b7107b438f7050d00a26f71f012f23b9/WzComparerR2/FrmPatcher.cs#L280

5. Replacing FrmPatcher.cs with the WCR2-CMS fork equivalent fixes the error, but it is currently unknown what is causing it.

Here is the relevant portion of the log:
```
Checking the pre-patch checksum: locales\vi.pak Completed
Checking the pre-patch checksum: locales\zh-CN.pak Completed
Checking the pre-patch checksum: locales\zh-TW.pak Completed
Checking the pre-patch checksum: natives_blob.bin Completed
Checking the pre-patch checksum: nmcogame64.dll Completed
Checking the pre-patch checksum: nps64.dll Completed
Checking the pre-patch checksum: ssleay32.dll Completed
Checking the pre-patch checksum: swiftshader\libEGL.dll Completed
Checking the pre-patch checksum: swiftshader\libGLESv2.dll Completed
[MapleStory.exe] Patching
  Creating temporary files...
  Checking post-patch checksum...System.Exception: CheckSum Error on "MapleStory.exe"(0). (0x90db0ba8, 0xfebd1e91)
   at WzComparerR2.Patcher.WzPatcher.VerifyCheckSum(UInt32 checksum0, UInt32 checksum1, String fileName, String reason) in C:\Izzy\WzComparerR2\WzComparerR2\Patcher\WzPatcher.cs:line 879
   at WzComparerR2.Patcher.WzPatcher.CreateNewFile(PatchPartContext part, String tempDir) in C:\Izzy\WzComparerR2\WzComparerR2\Patcher\WzPatcher.cs:line 515
   at WzComparerR2.Patcher.WzPatcher.Patch(String mapleStoryFolder, String tempFileFolder) in C:\Izzy\WzComparerR2\WzComparerR2\Patcher\WzPatcher.cs:line 333
   at WzComparerR2.FrmPatcher.ExecutePatch(String patchFile, String msFolder, Boolean prePatch) in C:\Izzy\WzComparerR2\WzComparerR2\FrmPatcher.cs:line 280
```

My hypothesis is that it isn't specifically MapleStory.exe but rather something wrong with the entire Patch process.

**Comment by PirateIzzy** [comment]
@Kagamia @HikariCalyx
Including you two for reference

**Comment by Kagamia** [comment]
> 5. Replacing FrmPatcher.cs with the WCR2-CMS fork equivalent fixes the error, but it is currently unknown what is causing it.

So the issue is not caused by patcher implementation, but most likely an UI issue? 🤔

**Comment by PirateIzzy** [comment]
> So the issue is not caused by patcher implementation, but most likely an UI issue? 🤔

Possibly. I used DiffChecker to see the differences and while I do see a few noticeable code changes, I'm not sure which one is causing it.
https://www.diffchecker.com/5wh6TwA4/

**Comment by Kagamia** [comment]
L234: prepatch is force enabled
L276: files are sorted.

**Comment by PirateIzzy** [comment]
I will enable L234 and comment L276 and let you know what happens.

**Comment by PirateIzzy** [comment]
![image](https://github.com/PirateIzzy/WzComparerR2/assets/34289651/de398b98-c5f5-4cdf-a05c-b683b68b69fa)
Thank you, I can confirm that it now works. Was it due to L234, L276, or both?

**Comment by PirateIzzy** [comment]
Edit: It was due to L234, just tested it. Enabling and disabling L276 had no difference. This feature (which was originally pre-patch only) was causing it to break.
![image](https://github.com/PirateIzzy/WzComparerR2/assets/34289651/7f5c9299-0ac0-481b-9183-d4b9bab2d182)

**Comment by Kagamia** [comment]
so the original WcR2 potentially have the same issue when prepatch is checked.

Interesting, I use prepatch very often but never seen this error before. 😢

**Comment by PirateIzzy** [comment]
It seems that it only occurs in .NET 6.0 for some reason, that may be why.

**Comment by Kagamia** [comment]
Confirmed the same issue also found in WcR2-CMS-Net6.
So I can debug it by myself.

**Comment by Kagamia** [comment]
Please help to verify if https://github.com/Kagamia/WzComparerR2/commit/a0ad7dfe5711c00050e2f6b925f11285e6b9ca55 helps.

**Comment by PirateIzzy** [comment]
I can confirm that it works. Thank you:

![image](https://github.com/PirateIzzy/WzComparerR2/assets/34289651/f6af37a4-c970-4862-b870-d97372d18ea2)

**Comment by Kagamia** [comment]
Seems the `DeflateStream` is reimplemented in .Net6 to adapt `Span` related api.
Also I see very poor performance in .Net6 (debug build) at prepatch stage, need further investigation.

**Comment by PirateIzzy** [comment]
For now I will keep this issue open until we're both confident in it.
